src/tty/tty.zig

fix issue #16 
fix local_processing when input is full

FIX: issue #16

---

Makefile
dockerfile

add docker to the makefile for systems that doesn't have zig installed

ADD docker

---

src/ft/math.zig
src/kernel.zig
src/tty/tty.zig
src/tty/vt100.zig

FIX tty input

---

src/tty/keyboard.zig

FIX kb_read:

---

build.zig
src/boot.zig
src/c_headers.zig
src/c_headers/multiboot.h
src/kernel.zig

Add interface for the multiboot_info structure.

ADD multiboot_info:

---

Makefile
src/ft/ascii.zig
src/ft/mem.zig
src/kernel.zig
src/shell.zig
src/shell/builtins.zig
src/shell/helpers.zig
src/shell/token.zig
src/shell/utils.zig
src/tty/keyboard/us-std.zig
src/tty/tty.zig
src/tty/vt100.zig

Adding a basic shell with quote-aware tokenization for improved command parsing.
Includes builtins and help functionality.

ADD basic shell:

---

build.zig
src/tty/keyboard.zig
src/tty/tty.zig
src/tty/vt100.zig

handle scrolling directly in the make_break function
also add a "posix" compilation option to enable strict posix conformance
close #30

FIX: issue #30

---

src/tty/tty.zig

fix '\v' 
fix characters ignored by echoctl
close #43 
close #49

fix #43 and #49

---

src/boot.zig

Add a panic function to catch kernel panic and logging error message.

ADD panic function:

---

src/multiboot.zig

FIX multiboot

---

src/ft/math.zig
src/ft/mem.zig

add:
- mem.alignBackward
- mem.alignForward
- math.divCeil
resolve #54

ADD functions to libft:

---

src/shell/builtins.zig
src/shell/helpers.zig
src/shell/utils.zig

add a command to show the content of the mmap multiboot tag

ADD mmap command:

---

src/ft/fmt.zig
src/shell/builtins.zig
src/shell/helpers.zig

add hexdump command that dump an area in the memory
close #45

add hexdump

---

src/ft/fmt.zig

FIX parseInt

---

src/shell/builtins.zig
src/shell/utils.zig

hexdump now work with zero ptr and does not overflow.
fix #71

FIX hexdump

---

Makefile
src/shell.zig
src/shell/builtins.zig
src/shell/helpers.zig
src/shell/utils.zig
src/tty/keyboard/keymap.zig
src/tty/keyboard/keymap_index.zig
src/tty/keyboard/keymaps/french.zig
src/tty/keyboard/keymaps/us-std.zig

add french keymap and a shell command to easily switch between keymaps
refactor shell

ADD french keymap:

---

src/memory/mapping.zig
src/memory/page_frame_allocator.zig
src/memory/virtual_page_allocator.zig

add getters for page_frame_descriptor in virtual_page_allocator and page_frame_allocator

ADD getter for page_frame_descriptor:

---

Makefile
src/memory/bitmap.zig

Adding a basic bitmap using an array of usize to store bits information

ADD basic bitmap:

---

src/memory.zig
src/memory/mapping.zig
src/memory/virtual_page_allocator.zig
src/multiboot.zig
src/shell/builtins.zig
src/shell/utils.zig

User space is owned by User.
Kernel space is owned by supervisor.
read only section of the kernel are set to read only (for extra safety)

ADD permissions in mapping:

---

src/kernel.zig
src/memory.zig
src/memory/buddy_allocator.zig
src/memory/linear_allocator.zig
src/memory/page_frame_allocator.zig
src/memory/paging.zig
src/memory/virtual_page_allocator.zig

use the Bitmap container in buddy allocator
buddy allocator now support non power-of-two allocation sizes

fix buddy allocator bitmap

---

src/boot.zig
src/drivers/acpi/acpi.zig
src/memory/mapping.zig
src/shell/builtins.zig

Mapping ACPI stuff to virtual memory.
We can now shut down our system!
YIP YIP
close #102

REWORK ACPI:

---

Makefile
src/boot.zig
src/drivers/acpi/acpi.zig
src/drivers/ps2/ps2.zig
src/ft/ft.zig
src/ft/log.zig
src/logger.zig
src/screen_of_death.zig

Adding the ft log based on the std log.
close #77

ADD ft log:

---

.github/workflows/build.yml
Makefile

Adding a basic CI to check the build stage.
related to #5

ADD CI build:

---

.github/workflows/ci.yml
build.zig
src/drivers/acpi/acpi.zig
src/drivers/ps2/ps2.zig
src/ft/Random.zig
src/ft/array_list.zig
src/ft/fmt.zig
src/ft/math.zig
src/linker.ld
src/memory.zig
src/memory/bitmap.zig
src/memory/buddy_allocator.zig
src/memory/cache.zig
src/memory/physical_memory.zig
src/memory/slab.zig
src/memory/virtual_memory.zig
src/memory/virtual_space_allocator.zig
src/multiboot.zig
src/shell.zig
src/shell/builtins.zig
src/shell/token.zig
src/shell/utils.zig
src/tty/keyboard.zig
src/tty/keyboard/keymap.zig
src/tty/themes.zig
src/tty/tty.zig
src/tty/vt100.zig

Reworking the whole project to fix errors introduced with zig 0.12.

REWORK 0.12

---

src/boot.zig
src/drivers/acpi/acpi.zig
src/drivers/acpi/types/acpi.zig
src/drivers/pit/pit.zig
src/interrupts.zig
src/memory.zig
src/memory/virtual_space.zig
src/shell/default/builtins.zig
src/tty/keyboard.zig

Add a basic PIT driver.
Rework ACPI initialization to use the PIT instead of busy loop.
close #138

driver PIT

---

src/drivers/acpi/acpi.zig
src/drivers/pit/pit.zig
src/shell/default/builtins.zig

Rename wait functions for sleep.
Fix typo in log message.
Close #164

REWORK PIT Driver

---

.github/workflows/build.yml
.github/workflows/unit_tests.yml
src/cpu.zig
src/gdt.zig
src/linker.ld
src/memory/object_allocators/page_grained_allocator.zig
src/memory/regions.zig
src/memory/virtual_space.zig
src/shell/default/builtins.zig
src/syscall/write.zig
src/trampoline.zig
src/userspace.poc.zig

Add a POC to reach ring 3 and to test syscall interface

add a poc for userspace

---

src/ft/fmt.zig
src/ft/io.zig
src/ft/io/counting_writer.zig
src/ft/io/fixed_buffer_stream.zig

add comptime print

---

README.md

<table>
<th>Preview light theme</th>
<th>Preview dark theme</th>
<tr>
<td>
</td>
<td>
</td>
</table>

ADD logo / header in readme

---

src/ft/ft.zig
src/ft/linked_list.zig

Add ft SinglyLinkedList and DoublyLinkedList, following the interface defined by the zig std library.

ADD ft linked_list:

---

src/ft/fmt.zig
src/ft/io/fixed_buffer_stream.zig
src/ft/math.zig
src/memory.zig
src/memory/object_allocators/page_grained_allocator.zig
src/memory/object_allocators/slab/cache.zig
src/memory/virtual_space.zig
src/multiboot.zig
src/shell/Shell.zig
src/task/signal.zig
src/task/task.zig
src/task/task_set.zig
src/task/wait.zig
src/tty/tty.zig

Jo/fix #197

---

src/boot.zig
src/ci.zig
src/kernel.zig
src/shell/default/builtins.zig
src/task/ready_queue.zig
src/task/scheduler.zig
src/task/task_set.zig

Add an idle task allowing us to block the current task (e.g. sleep) if the current task is the only task running.

ADD idle task:

---

src/userspace.poc.zig

Fix typo in section name.
close #208

REWORK userspace poc:

---

README.md
build/Makefiles/Zig.mk

- Update `Zig.mk` to improve version detection logic for Zig.
- Revamp `README.md` with detailed project overview, build instructions, and roadmap.

UPDATE Zig.mk & documentation:
